function write_s2p_file(filename, freq, S11, S21, S12, S22)
% 将S参数写入Touchstone S2P文件
%
% 输入：
%   filename - 输出文件名（.s2p）
%   freq     - 频率向量 (Hz)
%   S11      - S11复数向量
%   S21      - S21复数向量
%   S12      - S12复数向量（可选，默认=S21，假设互易）
%   S22      - S22复数向量（可选，默认=S11，假设对称）

    if nargin < 5
        S12 = S21;  % 假设互易
    end

    if nargin < 6
        S22 = S11;  % 假设对称
    end

    % 检查向量长度
    n = length(freq);
    if length(S11) ~= n || length(S21) ~= n
        error('S11, S21的长度必须与freq相同');
    end

    fprintf('写入S2P文件: %s\n', filename);

    % 打开文件
    fid = fopen(filename, 'w');
    if fid == -1
        error('无法创建文件: %s', filename);
    end

    % 写入文件头
    fprintf(fid, '! Touchstone S2P file\n');
    fprintf(fid, '! Generated by MATLAB\n');
    fprintf(fid, '! Date: %s\n', datestr(now));
    fprintf(fid, '# HZ S MA R 50\n');  % 频率单位Hz, S参数, 幅度-角度, 50欧姆
    fprintf(fid, '!\n');
    fprintf(fid, '! Freq(Hz)  S11_mag  S11_ang  S21_mag  S21_ang  S12_mag  S12_ang  S22_mag  S22_ang\n');
    fprintf(fid, '!\n');

    % 写入数据
    for i = 1:n
        fprintf(fid, '%.6e  %.6e  %.6e  %.6e  %.6e  %.6e  %.6e  %.6e  %.6e\n', ...
                freq(i), ...
                abs(S11(i)), angle(S11(i))*180/pi, ...
                abs(S21(i)), angle(S21(i))*180/pi, ...
                abs(S12(i)), angle(S12(i))*180/pi, ...
                abs(S22(i)), angle(S22(i))*180/pi);
    end

    fclose(fid);

    fprintf('  成功写入 %d 个数据点\n', n);
    fprintf('  频率范围: %.2f ~ %.2f GHz\n', min(freq)/1e9, max(freq)/1e9);

end
